import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Main from "../components/Main.jsx";
import context from "../context/Context";
import React from "react";
import Footer from "../components/Footer";

export default function Home() {
  const [active, setActive] = React.useState(0);
  const activePage = e => {
    setActive(e);
  };

  return (
    <div className="bg-gray-800 w-full h-full">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <context.Provider value={{ activePage, active, setActive }}>
        <Header />
        <Main />
        <Footer/>
        
      </context.Provider>

      <footer></footer>
    </div>
  );
}
