import Head from "next/head";
import Header from "../components/Header";
import Main from "../components/Main.jsx";
import React from "react";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className="bg-gray-800 w-full h-full">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
      <Footer />

     
    </div>
  );
}
